name: Test workflow
on: push
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint sources
        run: npm run lint

  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set environment
        run: export NPM_CONFIG_PREFIX=~

      - name: Install dependencies
        run: npm install --no-save

      - name: Install Truffle
        run: npm install --no-save truffle@5.2.4

      - name: Run tests
        run: npm run test
